# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4d989ef4c2c3967ec66920fb0a370a46247b67bb66d70fe97b6f2e48c8c15f564ce77635ebf0358131b2b3affe51cab1b1e19583093ef098a9d4d0f886df81e

test:
  secret_key_base: c3040000fe73098191f26bbab04280b4020a41e70cd25c7d23a6f7759f0d10b9e18ac6e674badb546cc33d6ea659ba22d2eb63ec43e68b126cf478f30c3e8296

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
